// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL-agVIehXP8_7137LHAcoqHhitSJDuN0',
    appId: '1:131704595055:web:b95b9d43b21016f60ae39a',
    messagingSenderId: '131704595055',
    projectId: 'campfire-f336b',
    authDomain: 'campfire-f336b.firebaseapp.com',
    storageBucket: 'campfire-f336b.appspot.com',
    measurementId: 'G-L94J5R3M6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ8fa0tJB1psTTBBMZK4eOLOCO64RI3rw',
    appId: '1:131704595055:android:324b8652bf5a041b0ae39a',
    messagingSenderId: '131704595055',
    projectId: 'campfire-f336b',
    storageBucket: 'campfire-f336b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJVzyCWn3VLBr7Gi_JETccrc8NwEJmoI',
    appId: '1:131704595055:ios:b1294e074415b72c0ae39a',
    messagingSenderId: '131704595055',
    projectId: 'campfire-f336b',
    storageBucket: 'campfire-f336b.appspot.com',
    androidClientId: '131704595055-st5ntgehb84qjrvgh7mcef6ms74edk76.apps.googleusercontent.com',
    iosClientId: '131704595055-b5lfo6p25s4qh0rs9ka05q27nkd3v9la.apps.googleusercontent.com',
    iosBundleId: 'com.example.campfire',
  );
}
